### ISSUE TITLE
where is the papaer?

### ISSUE THREAD

**Issue by marscep456** [ZYangChen/MoCha-Stereo#1]
Hi  great works! but Where can I get a download link for this paper?

**Comment by ZYangChen** [comment]
Thank you for your question.  A camera-ready version of the manuscript has been submitted to the CVPR official; the exact visible time needs to be subject to the CVPR official. In addition, we have no plans to release a preprint. If you would like to see the manuscript in advance, please contact me at ziyangchen2000 AT gmail DOT com

**Comment by ZYangChen** [comment]
Thank you for your interest. Preprint paper is available [here](https://arxiv.org/abs/2404.06842).
