### ISSUE TITLE
请问这个项目如何可视化推理的结果呢

### ISSUE THREAD

**Issue by LiJiajun000322** [ZYangChen/MoCha-Stereo#10]
请问如何获得模型推理出的视察图呢？

**Comment by LiJiajun000322** [comment]
然后我想再请问一下这个项目里如何去推理单独的一张图呢，能不能提供一下这个功能呢

**Comment by LiJiajun000322** [comment]
另外的话我还想再请教一下，我生成的视差图为什么是灰色的灰度图呢，而您的demo视频中却是彩色的，我是哪里出现问题了吗请问。

**Comment by ZYangChen** [comment]
可以参考RAFT-Stereo的[demo.py](https://github.com/princeton-vl/RAFT-Stereo/blob/main/demo.py)实现这一功能

**Comment by LiJiajun000322** [comment]
好的，我已经实现了可视化推理结果的功能，还想再次请教一下为什么生成的视差图是灰度图呢。

**Comment by ZYangChen** [comment]
> 好的，我已经实现了可视化推理结果的功能，还想再次请教一下为什么生成的视差图是灰度图呢。

你好，我的[上述回答](https://github.com/ZYangChen/MoCha-Stereo/issues/10#issuecomment-2267289712)就是在回答如何生成彩色的视差图的问题。保存成灰度图或是彩色图与保存格式有关，可以参考RAFT-Stereo的[demo.py](https://github.com/princeton-vl/RAFT-Stereo/blob/main/demo.py)实现保存成彩色图的功能。

**Comment by zyh778** [comment]
> 然后我想再请问一下这个项目里如何去推理单独的一张图呢，能不能提供一下这个功能呢

请问你是如何推理单独的一张图像比如左视图，并生成左视差图的呢？
