### ISSUE TITLE
Unable to find the implementation for reconstruction error

### ISSUE THREAD

**Issue by SUGDW** [ZYangChen/MoCha-Stereo#11]
I'm trying to find the implementation of reconstruction error $E$ described in Eq. (7): 
$$E=K_l(R-\frac{TN^T}D)K_r^{-1}I_r-I_l$$
but all i can find is a function called 'disp_wrap' on the line 220 of 'refinement.py':
~~~python
wraped_right = disp_wrap(right_img, idsp)[0]
flaw = wraped_right - left_img
~~~
looks very similar to Eq. (7), but without any configuration about camera intrinsic.

**Comment by ZYangChen** [comment]
Available [here](https://github.com/ZYangChen/MoCha-Stereo/blob/main/nets/warp.py).
