### ISSUE TITLE
LSTMMultiUpdateBlock calls missing parameter

### ISSUE THREAD

**Issue by AdrienGhariani** [ZYangChen/MoCha-Stereo#12]
Hello,

There seem to be an issue with how LSTMMultiUpdateBlock is called.
The two first self.update_blockcalls are missing the netC parameter so the code is not running as is for me.

1 - self.update_block(net_list, inp_list, iter16=True, iter08=False, iter04=False, update=False)
2 - self.update_block(net_list, inp_list, iter16=self.args.n_gru_layers==3, iter08=True, iter04=False, update=False)
3 - self.update_block(netC, net_list, inp_list, geo_feat, disp,
                                                                  iter16=self.args.n_gru_layers == 3,
                                                                  iter08=self.args.n_gru_layers >= 2)

Thank you

**Comment by ZYangChen** [comment]
Only the third "update block" is called here.
