### ISSUE TITLE
询问可视化问题

### ISSUE THREAD

**Issue by xiaorenwu234** [ZYangChen/MoCha-Stereo#15]
你好作者，我现在在运行你的代码之后注意到只能够输出一个日志，我想请问一下能否以深度图的形式可视化

**Comment by ZYangChen** [comment]
你好，可以通过[demo.py](https://github.com/ZYangChen/MoCha-Stereo/blob/main/MoCha-Stereo/demo.py)加载权重，并实现视差图的可视化。

**Comment by xiaorenwu234** [comment]
好的谢谢

**Comment by ZYangChen** [comment]
不客气。需要安装额外的库matplotlib
`
pip install matplotlib
`
