### ISSUE TITLE
no official_train.txt

### ISSUE THREAD

**Issue by tangconghui2008** [ZYangChen/MoCha-Stereo#16]
![image](https://github.com/user-attachments/assets/dcdfbc22-7ec8-41eb-9a1f-31d92d9d609c)
![image](https://github.com/user-attachments/assets/00923dd8-62fc-4a95-af98-3d6c3f0fe2c4)

Thank you for the author's great work. When I am replicating the code, I followed the steps on GitHub and downloaded the dataset from both the "middlebury submit" and "datasets" options. However, when I run the evaluate_stereo.py code, it prompts "No such file or directory: 'datasets/Middlebury/MiddEval3/official_train.txt'". Is it because the dataset has been changed, or is there an issue with my operations? I hope you can provide an answer. Thank you.

**Comment by ZYangChen** [comment]
"official_train.txt" is available at [here](https://github.com/ZYangChen/MoCha-Stereo/blob/main/official_train.txt).
