### ISSUE TITLE
feature.py was deleted

### ISSUE THREAD

**Issue by Huaixv17** [ZYangChen/MoCha-Stereo#17]
Hello, thank you for your outstanding work. I would like to ask why the feature.py file was deleted. Thank you for your reply.

**Comment by ZYangChen** [comment]
Thank you for your attention. I am adjusting the structure of this project. "[feature.py](https://github.com/ZYangChen/MoCha-Stereo/blob/main/MoCha-Stereo/nets/feature.py)" is available now.
