### ISSUE TITLE
请问MCA是如何更关注边缘信息的？

### ISSUE THREAD

**Issue by DLUTTengYH** [ZYangChen/MoCha-Stereo#2]
在论文中您写到f_pre = F(f - G(f))， 其中G是高通滤波器，所以应该只有高频信息也就是边缘会通过，那么f-G(f)会将这些边缘信息变成0，而低频信息不变，那么我在求和的时候，高频信息的响应值应该更低才对啊，为什么会更关注重复的几何结构呢？这里不是很理解，麻烦您解答一下，万分感谢！

**Comment by ZYangChen** [comment]
感谢您的提问，是我笔误了。G不是高斯**高通**滤波器，是高斯**低通**滤波器。MCA用特征f减去G(f)平滑后的结果，通过衰减低频分量，实现高通滤波的效果。我们通过这种高频信息关注重复的几何结构。
G是低通滤波才与我们的代码是一致的。此外，我们在Arxiv版本上修正了这一笔误，请以该版本为准。相当感谢您的这个问题！

**Comment by ZYangChen** [comment]
Thank you for your question. I made a writing mistake. **G** stands for Gaussian **low-pass** filter. We attenuate the low frequency components to achieve a high pass filter effect.  This is consistent with our code and we will open source the code for the algorithm. We also fixed this typo on arxiv. Thanks again for your question!
![wrong1](https://github.com/ZYangChen/MoCha-Stereo/assets/108012397/958a3a32-1f31-428b-91fe-65b0454d7335)
![right1](https://github.com/ZYangChen/MoCha-Stereo/assets/108012397/902229a6-7abb-4bfd-ab41-dce460e572a8)

**Comment by ZYangChen** [comment]
您好，兄弟！我认为我完成了这个问题的回答，所以我准备关闭这个问题。如果您仍然有疑问，可以重新打开问题评论，我们继续交流，谢谢！
