### ISSUE TITLE
ONNX export

### ISSUE THREAD

**Issue by valeriopaolicelli** [ZYangChen/MoCha-Stereo#21]
Hello,

Thank you for your great work! Do you have any plans to publish a script to export MoCha-Stereo in ONNX format and speed up inference on CPU-only hosts?

**Comment by ZYangChen** [comment]
Thank you for the wonderful suggestions. I believe this will have significant implications for stereo matching applications. However, I am currently very busy and do not have plans to export the ONNX format at this time. If you urgently need this format, you can refer to [this project](https://github.com/pcb9382/StereoAlgorithms) for guidance.

**Comment by valeriopaolicelli** [comment]
Thank you for your reply. I tried to export the ONNX model but got an error with a MoCha-Stereo layer. I post the error here and attach my script in this issue, in case others want to investigate the problem and can use it as a starting point.
[export_onnx.zip](https://github.com/user-attachments/files/18127447/export_onnx.zip)

> python export-notworking.py --dynamic
```
Unsupported: ONNX export of convolution for kernel of unknown shape.  [Caused by the value '36892 defined in (%36892 : Float(*, 384, *, *, strides=[786432, 2048, 64, 1], requires_grad=1, device=cpu) 
= onnx::Concat[axis=1](%3694, %5157), scope: core.mocha_stereo.Mocha::/nets.MCCV.Mca_Camp::mccv # /MoCha-Stereo/MoCha-Stereo/nets/MCCV.py:41:0
)' (type 'Tensor') in the TorchScript graph. The containing node has kind 'onnx::Concat'.]
```

**Comment by ZYangChen** [comment]
> Thank you for your reply. I tried to export the ONNX model but got an error with a MoCha-Stereo layer. I post the error here and attach my script in this issue, in case others want to investigate the problem and can use it as a starting point. [export_onnx.zip](https://github.com/user-attachments/files/18127447/export_onnx.zip)
> 
> > python export-notworking.py --dynamic
> 
> ```
> Unsupported: ONNX export of convolution for kernel of unknown shape.  [Caused by the value '36892 defined in (%36892 : Float(*, 384, *, *, strides=[786432, 2048, 64, 1], requires_grad=1, device=cpu) 
> = onnx::Concat[axis=1](%3694, %5157), scope: core.mocha_stereo.Mocha::/nets.MCCV.Mca_Camp::mccv # /MoCha-Stereo/MoCha-Stereo/nets/MCCV.py:41:0
> )' (type 'Tensor') in the TorchScript graph. The containing node has kind 'onnx::Concat'.]
> ```

Thank you for your contribution!
