### ISSUE TITLE
您好，请问将IGEV的特征提取网络替换后参数变大，为什么运行时候会从37s减少为33s呢

### ISSUE THREAD

**Issue by 1434205229** [ZYangChen/MoCha-Stereo#22]

**Comment by ZYangChen** [comment]
我认可参数量可以作为模型推理速度的一个参考，不过理论上说，参数量和实际的推理速度之间没有直接的关系。33s是我们实机测试的结果。

**Comment by ZYangChen** [comment]
我们使用的预训练模型参数量更大一点. 不过这部分权重是冻结的.

**Comment by 1434205229** [comment]
谢谢您的回复，我还有2个问题。
![image](https://github.com/user-attachments/assets/46d451a0-48cb-4d1c-85d6-6c764362a502)
1.这个地方的基线模型是否也将IGEV的conGRUs替换为conLSTM了
2.使用conLSTM会比使用conGRUs效果好嘛
