### ISSUE TITLE
您好，请问您所提供的代码是训练sceneflow的cleanpass吗？如果我想训练finalpass是否要改为IGEV中的SceneFlowDatasets

### ISSUE THREAD

**Issue by 1434205229** [ZYangChen/MoCha-Stereo#23]
![image](https://github.com/user-attachments/assets/adc7dd16-8df3-4e4a-b744-77bd09dafdf9)
![image](https://github.com/user-attachments/assets/47164bda-2266-4ecb-b85f-bf874c618e32)
![image](https://github.com/user-attachments/assets/fc3715bb-686e-41bb-97e0-68a4aae2efc6)
这些路径好像是cleanpass数据集的路径

**Comment by 1434205229** [comment]
这是我的数据集文件夹
├── sceneflow
        ├── frames_finalpass
        ├── disparity

**Comment by 1434205229** [comment]
我明白了 我改下数据集的顺序

**Comment by 1434205229** [comment]
您好，再打扰一下，我看您的stereo_datasets参考的是RAFT，验证集取的是scenflow测试集中的400个，而IGEV的验证集取全部的sceneflow测试集，这是否对指标有所影响
![image](https://github.com/user-attachments/assets/2da95cae-cf7b-4c83-b4ba-d64dd36b62a5)

**Comment by yyYcoco2** [comment]
请问有回复了吗

**Comment by lsyl20** [comment]
> 您好，再打扰一下，我看您的stereo_datasets参考的是RAFT，验证集取的是scenflow测试集中的400个，而IGEV的验证集取全部的sceneflow测试集，这是否对指标有所影响 ![image](https://github.com/user-attachments/assets/2da95cae-cf7b-4c83-b4ba-d64dd36b62a5)

请问有回复了吗，我也是使用400个进行测试才能得到论文中的结果
