### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by ZYangChen** [ZYangChen/MoCha-Stereo#3]
There is a writing error in the paper published on cvpr. Please refer to the [Arxiv version](https://arxiv.org/abs/2404.06842).
![wrong1](https://github.com/ZYangChen/MoCha-Stereo/assets/108012397/958a3a32-1f31-428b-91fe-65b0454d7335)
![right1](https://github.com/ZYangChen/MoCha-Stereo/assets/108012397/902229a6-7abb-4bfd-ab41-dce460e572a8)

**Comment by ZYangChen** [comment]
**G** stands for Gaussian low-pass filter. We attenuate the low frequency components to achieve a high pass filter effect. This is consistent with our code and we will open source the code for the algorithm.

**Comment by ZYangChen** [comment]
> **G** stands for Gaussian low-pass filter. We attenuate the low frequency components to achieve a high pass filter effect. This is consistent with our code and we will open source the code for the algorithm.

Code is now available.

**Comment by YHCks** [comment]
![image](https://github.com/user-attachments/assets/0cb7eb75-71ee-4063-9aa3-71ab4adca830)
您好我想问一下，我这里有点不太明白，希望您可以解答一下，这个公式，他滑动窗口中的i和j为什么是从1开始，那样得到的滑动窗口不就没有包含h和w吗

**Comment by ZYangChen** [comment]
> ![image](https://private-user-images.githubusercontent.com/133937084/376190940-0cb7eb75-71ee-4063-9aa3-71ab4adca830.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5OTU2OTksIm5iZiI6MTczMTk5NTM5OSwicGF0aCI6Ii8xMzM5MzcwODQvMzc2MTkwOTQwLTBjYjdlYjc1LTcxZWUtNDA2My05YWEzLTcxYWI0YWRjYTgzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQwNTQ5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmE0OTAwOTU5YTVjYjkxNmYzZGE3YWM1MGJmNzU3MjQwMzdmNGQzY2Q0YjVjOTQ2NTRhMDFhOTE3YmUyZmU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vs2ShcoheTKxDLFHbdkBikRE2VCK_5Gg709gHxCt9mM) 您好我想问一下，我这里有点不太明白，希望您可以解答一下，这个公式，他滑动窗口中的i和j为什么是从1开始，那样得到的滑动窗口不就没有包含h和w吗

确实，应该从0开始。代码实现是对的，公式这里错了。
