### ISSUE TITLE
请问大概什么时候会公开源码呢？

### ISSUE THREAD

**Issue by zylo117** [ZYangChen/MoCha-Stereo#4]

**Comment by ZYangChen** [comment]
您好，朋友。感谢您的关注！
1. 我们将在24年7月在本仓库公开源代码。
2. 贵州大学的研究人员无需联系我索要代码，因为我已经在[内部仓库](https://github.com/GZU-ZhangYJ-group/mocha-stereo-early-access)发布代码了，直接申请访问仓库即可。

有其他最新的消息我会在这个项目的主页更新。如果您担心错过更新的消息，也可以评论留下邮箱，我更新的时候也发一封邮件给您

-----------------------------------------------------------------------------------------
Hello, friend. Thank you for your attention! MoCha-Stereo will be released in this repository in **July, 2024**. 

I'll update the home page of this project with any other updates. If you're worried about missing an update, you can also leave an email in the comments and I'll send you an email when I do!

**Comment by ahtso** [comment]
> Owner

先感謝作者的分享，論文效果看起來絕佳！
如果有更新開源程式碼，也麻煩您通知！
mail: train6602@gmail.com

Thanks a lot.

**Comment by ZYangChen** [comment]
> > Owner
> 
> 先感謝作者的分享，論文效果看起來絕佳！ 如果有更新開源程式碼，也麻煩您通知！ mail: [train6602@gmail.com](mailto:train6602@gmail.com)
> 
> Thanks a lot.

好的

**Comment by wwxb2012** [comment]
您好，现在已经7月了，大概啥时候发啊

**Comment by ZYangChen** [comment]
> 您好，现在已经7月了，大概啥时候发啊

您好，发了。如果觉得这个工作有帮助，可以给我一个免费的star吗(∩_∩)

**Comment by wwxb2012** [comment]
> > 您好，现在已经7月了，大概啥时候发啊
> 
> 您好，发了。如果觉得这个工作有帮助，可以给我一个免费的star吗(∩_∩)

没问题，给了
