### ISSUE TITLE
关于tf_efficientnetv2_l检查点的问题

### ISSUE THREAD

**Issue by ChenhuiShen** [ZYangChen/MoCha-Stereo#6]
作者您好，我找不到对应的 tf_efficientnetv2_l 权重文件，您是否可以提供对应的权重文件下载地址，感谢！

**Comment by ChenhuiShen** [comment]
已解决

**Comment by ZYangChen** [comment]
ok 这个权重确实可以下载到, 或者直接用timm库加载权重也可以下载

**Comment by ahtso** [comment]
作者您好，關於 timm pretrained  weights of "tf_efficientnetv2_l" 
這個連結似乎死亡了，我多次重新載入都無法完整地把weights存下來，導致無法繼續
能否提供額外的雲端連結呢，謝謝

**Comment by ZYangChen** [comment]
> 作者您好，關於 timm pretrained weights of "tf_efficientnetv2_l" 這個連結似乎死亡了，我多次重新載入都無法完整地把weights存下來，導致無法繼續 能否提供額外的雲端連結呢，謝謝

https://github.com/ZYangChen/MoCha-Stereo/releases/download/tf_efficientnetv2_l-d664b728/tf_efficientnetv2_l-d664b728.pth
