### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sestras** [ZYangChen/MoCha-Stereo#7]
Hello,

Thank you for your great work and for publishing the code for your model. Could you please add a license so it is clear how the code in this repository can be used? You state that you borrowed code from [IGEV](https://github.com/gangweiX/IGEV), [RAFT-Stereo](https://github.com/princeton-vl/RAFT-Stereo), [GwcNet](https://github.com/xy-guo/GwcNet). All of them use MIT license, so this might be a good choice, but it is, of course, at your discretion.

Thank you!

**Comment by ZYangChen** [comment]
Thank you for your reminder. The MIT licence is now available.
