### ISSUE TITLE
关于预训练权值

### ISSUE THREAD

**Issue by FBSalol** [ZYangChen/MoCha-Stereo#8]
![da5fa30e56fc3bafa3aa87b401da294](https://github.com/user-attachments/assets/b305dcc9-6c7f-4473-829a-19691e3df9fb)
作者你好，
能不能分享一下预训练的权重：）

**Comment by ZYangChen** [comment]
您好，这个问题已经在issue #6 回答过了。您也可以在[这里](https://github.com/ZYangChen/MoCha-Stereo/releases/download/tf_efficientnetv2_l-d664b728/tf_efficientnetv2_l-d664b728.pth)下载到权重。
