### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by wwxb2012** [ZYangChen/MoCha-Stereo#9]
File "MoCha-Stereo/evaluate_stereo.py", line 14, in <module>
    from mocha_stereo import Mocha, autocast
  File "MoCha-Stereo/core/mocha_stereo.py", line 5, in <module>
    from core.extractor import MultiBasicEncoder, Feature, SpatialInfEncoder
ImportError: cannot import name 'SpatialInfEncoder' from 'core.extractor' (MoCha-Stereo/core/extractor.py)

**Comment by wwxb2012** [comment]
It seems like removing "SpatialInfEncoder" can solve this problem, however, i got another problem: when I run "python evaluate_stereo.py --restore_ckpt models/mocha-stereo.pth --dataset kitti", I found that the download of "tf_efficientnetv2_l-d664b728.pth" is needed. But where to put this file?

**Comment by ZYangChen** [comment]
> File "MoCha-Stereo/evaluate_stereo.py", line 14, in from mocha_stereo import Mocha, autocast File "MoCha-Stereo/core/mocha_stereo.py", line 5, in from core.extractor import MultiBasicEncoder, Feature, SpatialInfEncoder ImportError: cannot import name 'SpatialInfEncoder' from 'core.extractor' (MoCha-Stereo/core/extractor.py)

Yes, 'SpatialInfEncoder' is not needed here. Thanks for the heads up, I've fixed the bug now!

**Comment by ZYangChen** [comment]
> It seems like removing "SpatialInfEncoder" can solve this problem, however, i got another problem: when I run "python evaluate_stereo.py --restore_ckpt models/mocha-stereo.pth --dataset kitti", I found that the download of "tf_efficientnetv2_l-d664b728.pth" is needed. But where to put this file?

I've already answered the question about weights in issues #6  and   #8 . You can call the timm library directly to get this weight. Or click [here](https://github.com/ZYangChen/MoCha-Stereo/releases/download/tf_efficientnetv2_l-d664b728/tf_efficientnetv2_l-d664b728.pth) to download it.
